parameters:
    da_oauth_client.user_provider.class: Da\OAuthClientBundle\Security\Core\User\FOSUBUserProvider
    da_oauth_client.user.class:          Da\OAuthClientBundle\Entity\User

services:
    da_oauth_client.user_provider:
        class: %da_oauth_client.user_provider.class%
        parent: hwi_oauth.user.provider.fosub_bridge.def
        arguments: [@fos_user.user_manager, null, %da_oauth_client.user.class%]
        abstract: true