parameters:
    da_oauth_client.identity_selector.default.class:     Da\OAuthClientBundle\Identity\BasicIdentitySelector
    da_oauth_client.request.processor.class:             Da\OAuthClientBundle\Request\RequestProcessor
    da_oauth_client.user_provider.fosub.class:           Da\OAuthClientBundle\Security\Core\User\FOSUBUserProvider
    da_oauth_client.user_provider.memory.class:          Da\OAuthClientBundle\Security\Core\User\MemoryUserProvider
    da_oauth_client.user.fosub.class:                    Da\OAuthClientBundle\Entity\FosUser
    da_oauth_client.user.memory.class:                   Da\OAuthClientBundle\Model\MemoryUser
    da_oauth_client.authorization_refresher.oauth.class: Da\OAuthClientBundle\Security\OAuthRefresher
    da_oauth_client.event.exception_listener.class:      Da\OAuthClientBundle\Event\ExceptionListener

services:
    da_oauth_client.identity_selector.default:
        class: %da_oauth_client.identity_selector.default.class%

    da_oauth_client.request.processor:
        class: %da_oauth_client.request.processor.class%
        arguments: [@hwi_oauth.http_client, @session]

    da_oauth_client.user_provider.fosub:
        class: %da_oauth_client.user_provider.fosub.class%
        parent: hwi_oauth.user.provider.fosub_bridge.def
        arguments: [@fos_user.user_manager, null, %da_oauth_client.user.class%]

    da_oauth_client.user_provider.memory:
        class: %da_oauth_client.user_provider.memory.class%
        arguments: [%da_oauth_client.user.memory.class%]

    da_oauth_client.authorization_refresher.oauth:
        class: %da_oauth_client.authorization_refresher.oauth.class%
        arguments: [@service_container]

    da_oauth_client.event.exception_listener:
        class: %da_oauth_client.event.exception_listener.class%
        arguments: [@http_kernel, @da_oauth_client.authorization_refresher.oauth]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }